
default: &default
  adapter: postgis
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restauranst_development
  username: andresor
  password: '1234'

test:
  <<: *default
  database: restauranst_test

production:
  <<: *default
  database: restauranst_production
  username: andresor
  password: <%= ENV["RESTAURANST_DATABASE_PASSWORD"] %>
  adapter: postgis
  url: <%= ENV.fetch("DATABASE_URL").gsub(/postgres/, 'postgis') %>
